language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_9adb3b53ca10_key -iv $encrypted_9adb3b53ca10_iv
 -in src/main/resources/application.properties.enc
 -out src/main/resources/application.properties -d
 -openssl aes-256-cbc -K $encrypted_352cccc6e72e_key -iv $encrypted_352cccc6e72e_iv -in application.properties.enc -out application.properties -d

